- name: Deploy MediFlow
  hosts: localhost
  become: yes

  tasks:

    - name: Install dependencies
      shell: pip3 install -r ../MediFlow-Hospital-Management-Platform/requirements.txt --break-system-packages

    - name: Run migrations
      shell: |
        cd ../MediFlow-Hospital-Management-Platform/hms
        python3 manage.py migrate

    - name: Start server
      shell: |
        cd ../MediFlow-Hospital-Management-Platform/hms
        nohup python3 manage.py runserver 0.0.0.0:8000 &